### PR TITLE
chore(Dockerfile): Use nginx:alpine for a smaller image size

### PR DESCRIPTION
**Pull request by cmckni3**

### CODE REVIEW

**Comment by gdi2290** [comment]
can you explain more of the difference here other than just the title

**Comment by thinkingmedia** [comment]
Alpine is a much smaller Linux image (5mb). I'm not sure this should be the default. It would be better to just add a comment in the Dockerfile to notify people that there is a smaller version. For production, people prefer stability over memory limits.

**Comment by cmckni3** [comment]
Yes, alpine makes the built image much smaller and it builds much faster.

I think alpine is pretty stable. The ability to easily install new software on top of the image is the only advantage I see with using the debian image.

**Comment by gdi2290** [comment]
as @thinkingmedia mentioned I rather it be a comment for users to opt into

**Comment by cmckni3** [comment]
ok see #1732

**Pull request closed without merging**
