### PR TITLE
BUILD_AOT Environment fix for windows builds

### PR DESCRIPTION
**Pull request by tsukhu**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug Fix

* **What is the current behavior?** (You can also link to an open issue here)
The windows build for npm run build:aot fails on windows as the environment variable does not get set as we get this error

'BUILD_AOT=1' is not recognized as an internal or external command,
operable program or batch file.

* **What is the new behavior (if this is a feature change)?**
This fix will work on both Windows and Unix/Linux environments as cross-env takes care of this.

* **Other information**:

### CODE REVIEW

**Comment by SherlockStd** [comment]
https://github.com/AngularClass/angular-starter/pull/1744/commits/dddc537f1e5b35ae5a3f020b2e383dbbe1ecafe5
You need to link to `node_modules/.bin/cross-env` or install globally. Please fix

**Comment by tsukhu** [comment]
@SherlockStd .. not sure why you need it globally . We have it in the dev dependencies already added in the package.json
"cross-env": "^5.0.0"

**Comment by gdi2290** [comment]
is this good?

**Comment by SherlockStd** [comment]
@tsukhu if you call it just with `cross-env`, not regarding on the OS, it will look at the path, and since the `node_modules` isn't in your path, I don't think it can work if it isn't installed globally, unless you link to the executable as I suggested, just like it's done for Webpack binaries:
```javascript
"webpack-dev-server": "node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js",
"webpack": "node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js"
```

**Comment by admosity** [comment]
@SherlockStd The `scripts` field is adds `.bin` to your path with npm:
https://docs.npmjs.com/misc/scripts#path

From the CI build, it's running
image

**Comment by SherlockStd** [comment]
Oh :astonished: My bad, thanks for the info :smile:

**Comment by tsukhu** [comment]
We are all good then!!

**Comment by tsukhu** [comment]
Added the lint fix as well now .. There was a build failure due to other updates related to lint

**Pull request merged**
